# Generated by Django 6.0.4 on 2026-05-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shorturl_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='total_clicks',
            new_name='total_dicks',
        ),
    ]
